version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  frontend:
    build:
      context: ./NewSpeak
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
