spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/newSpeak
    username: sa
    password:
  config:
    import: application-secret.yml
  cloud:
    gcp:
      storage:
        bucket: 'sentence_pro'
        project-id: 'steady-citron-435112-b2'
        credentials:
          location: 5e01616d4635ae3d07be55d482fad7567834f0c2.json

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    group:
      "local": "local, jwt, oauth"
    active: local

logging:
 level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace

server:
  port: 8080

gpt:
  api:
    url: https://api.openai.com/v1/chat/completions
    assistant:
      report:
    threads: https://api.openai.com/v1/threads
  prompt:
    report: 저는 이제부터 당신과 영어로 대화할 것입니다. 당신은 제가 준 뉴스 기사의 내용을 보고, 해당 내용을 주제로 적절한 응답을 한국인과의 회화 수준에서 영어로 제공하세요. 또한 당신은 해당 대화들을 모두 수집하여 마지막에 최종적으로 정해진 5개의 분야 (어휘력, 표현력, 이해력, 명확성, 문법) 에 각 20점을 만점으로 총 100점을 만점으로하는 점수를 기준으로 제공하시오. 그리고 각 분야에 대한 적절한 피드백도 일정한 기준을 가지고 제공하시오. 그리고 사용자와의 대화를 돌아보고, 특정 대화에서 바꾸었으면 좋았을 부분이나 더 나은 표현을 2~3개 정도 제시하시오.
  setting:
    model: gpt-4o-mini
    temperature: 2
    top-p: 0.6
    max-tokens: 16383
    frequency_penalty: 0
    presence_penalty: 0
    tool-choice: required