signUpUrl: http://j11e103.p.ssafy.io/register
mainUrl: http://j11e103.p.ssafy.io

# [jpa property]
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        generate-ddl: false
        format_sql: true
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버로 설정
    url: jdbc:mysql://j11e103.p.ssafy.io:3306/news_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: daechang
    password: 1234
    hikari: # HikariCP를 사용하는 경우
      maximum-pool-size: 10 # 예시 설정, 필요에 따라 조정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 168411646829-egpsufc783hcr4qqe02ejrk349aqgpnr.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

jwt:
  secretKey: 773f16283381c3ac99d1373f4fda6097d21922a6bb1c59eda62ac156637c3cf52e7cb6dd0b6818ceca2aad4f7d6b51a5d64c0c72c5ca6662612031a052e9dbba

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
